"""
Django settings for inventory_backend project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os

from pathlib import Path
from datetime import timedelta
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get('DEBUG') or 0)

# ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', default='').split(' ')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', default='').split(' ')

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split()
CSRF_TRUSTED_ORIGINS = ["https://*.rnp.br"]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'inventory_backend.urls'
TENANT_URLCONF = 'clients.urls'

UNFOLD = { 
    "SITE_TITLE": _("ChameleonMap Portal"),
    "SITE_HEADER": _("ChameleonMap Admin"),
    "SITE_SUBHEADER": _("Welcome to ChameleonMap Admin Portal"),
    "SITE_URL": "/admin",
    "SITE_ICON": "https://i.imgur.com/65Yiw9X.png",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": "https://i.imgur.com/65Yiw9X.png",
        },
    ],

}

# Multi-tenant settings
TENANT_MODEL = "clients.Client"
TENANT_DOMAIN_MODEL = "clients.Domain"
TENANT_USERS_DOMAIN = os.environ.get("DJANGO_BASE_DOMAIN", "localhost")
AUTH_USER_MODEL= "clients.TenantUser"

HAS_MULTI_TYPE_TENANTS = True
MULTI_TYPE_DATABASE_FIELD = 'tenancytype'

TENANT_TYPES = {
    "public": {
        "APPS": [
            'unfold',
            'django_tenants',
            'inventory_backend.apps_overrides.TenantPermissionsConfig',
            'tenant_users.tenants',
            'clients',
            'inventory_backend.apps_overrides.AxesConfig',
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'colorfield',
            'rest_framework',
            'corsheaders',
            'tinymce',
        ],
        "URLCONF": ROOT_URLCONF,
    },
    "root": {
        "APPS": [
            'unfold',
            'django_tenants',
            'inventory_backend.apps_overrides.TenantPermissionsConfig',
            'tenant_users.tenants',
            'inventory_backend.apps_overrides.AxesConfig',
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'colorfield',
            'rest_framework',
            'corsheaders',
            'tinymce',
        ],
        "URLCONF": ROOT_URLCONF,
    },
    "scoped": {
        "APPS": [
            'unfold',
            'administration.apps.AdministrationConfig',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'inventory_backend.apps_overrides.TenantPermissionsConfig',
        ],
        "URLCONF": TENANT_URLCONF,
    }
}

INSTALLED_APPS = []
for schema in TENANT_TYPES:
    INSTALLED_APPS += [app for app in TENANT_TYPES[schema]["APPS"] if app not in INSTALLED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

# Axes config (suspicious login middleware)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_FAIL_RETRY_LIMIT = 5
AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]]
AXES_CACHE = 'default'
AXES_ENABLE_ADMIN = True
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'tenant_users.permissions.backend.UserBackend',
]

CORS_ORIGIN_WHITELIST = (
    os.environ.get('CORS_WHITELIST'),
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'my_templatetag': 'administration.templatetags.importer_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'inventory_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": 'django_tenants.postgresql_backend',
        "HOST": 'db',
        "PORT": 5432,
        "NAME": os.environ.get("POSTGRES_DB", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("POSTGRES_USER", "user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', _('English')),
    ('pt', _('Portuguese')),
    ('es', _('Spanish')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# STATIC_URL = '/static/'
STATIC_URL = '/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "skin": "oxide-dark",
    "height": 300,
    "menubar": True,
    "plugins": "advlist,autolink,code,lists,link,image,charmap,print,preview,anchor,"
    "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
    "code,help,wordcount",
    "toolbar": "code | undo redo | formatselect | fontsizeselect | forecolor | link image |"
    "bold italic backcolor | alignleft aligncenter "
    "alignright alignjustify | outdent indent | "
    "removeformat | help",
}

# Email settings
# EMAIL_DUMMY controls whether Django uses the dummy email backend for testing.
# If EMAIL_DUMMY is True and DEBUG is enabled (development mode), emails will not be sent,
# and Django will use the dummy backend to simulate email sending.
# In all other cases (including production), real emails will be sent using the SMTP backend.
EMAIL_DUMMY = os.environ.get('EMAIL_DUMMY', 'False') == 'True'

if False:
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@chameleon-map.com.br')

LOGIN_URL = '/admin'
LOGIN_REDIRECT_URL = '/admin'
LOGOUT_REDIRECT_URL = '/admin'
