# Generated by Django 4.2.20 on 2025-04-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tenancytype',
            field=models.CharField(choices=[('public', 'Public'), ('scoped', 'Scoped'), ('root', 'Root')], default='scoped', max_length=100),
        ),
    ]
