# Generated by Django 5.0 on 2025-12-03 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_tenancytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True, validators=[django.core.validators.RegexValidator(message='Nome de domínio inválido. Use apenas letras, números, hífen (não no início/fim) e pontos.', regex='^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$')]),
        ),
    ]
