# Generated by Django 5.0 on 2025-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_domain_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(help_text='The domain will be generated automatically: if the Tenant Name is "wrnp-2026", the domain will be "wrnp-2026.mapa.rnp.br".', max_length=63, verbose_name='Tenant Name'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
    ]
