# Generated by Django 5.0 on 2026-03-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_slug_alter_domain_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tenancytype',
            field=models.CharField(choices=[('public', 'Public'), ('scoped', 'Scoped'), ('root', 'Root')], default='scoped', max_length=100, verbose_name='tenancy type'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True, verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
