# Generated by Django 5.0 on 2026-04-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_slug_alter_domain_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code2', models.CharField(max_length=2)),
                ('code4', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=25)),
                ('flag', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Language Options',
                'db_table': 'languageoptions',
            },
        ),
    ]
