# Generated by Django 5.0 on 2026-04-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_languageoption'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='languageoption',
            table='language_option',
        ),
    ]
