# Generated by Django 5.0 on 2026-04-20 18:17

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_languageoption_table'),
    ]

    operations = [
    ]
