# Generated by Django 5.0 on 2026-04-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20260420_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageoption',
            old_name='code2',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='languageoption',
            name='code4',
        ),
        migrations.RemoveField(
            model_name='languageoption',
            name='flag',
        ),
    ]
