# Generated by Django 5.0 on 2026-04-20 18:28

from django.db import migrations
from administration.language_codes import LanguageCode

def populate_language_options(apps, schema_editor):
    LanguageOption = apps.get_model('clients', 'LanguageOption')
    for code, name in LanguageCode.choices:
        LanguageOption.objects.get_or_create(code = code, defaults = {"name": name})

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_code2_languageoption_code_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_language_options)
    ]
