# Generated by Django 3.2.25 on 2025-04-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_auto_20250128_1400'),
        ('administration', '0031_auto_20250402_1424'),
    ]

    operations = [
    ]
