# Generated by Django 5.0 on 2026-03-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_merge_0021_auto_20250128_1400_0031_auto_20250402_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuNameTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=2000)),
                ('language_code', models.CharField(max_length=20)),
                ('menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.menu')),
            ],
            options={
                'db_table': 'menu_name_translations',
            },
        ),
    ]
