# Generated by Django 5.0 on 2026-03-18 23:58

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_merge_0021_auto_20250128_1400_0031_auto_20250402_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['hierarchy_level'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menugroup',
            options={'verbose_name': 'Menu Group', 'verbose_name_plural': 'Menu Groups'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='kml_shape',
            name='kml_file',
            field=models.FileField(help_text='Upload a custom KML file (max 30Mb).', upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['kml'])], verbose_name='KML file'),
        ),
        migrations.AlterField(
            model_name='kml_shape',
            name='links_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='links color'),
        ),
        migrations.AlterField(
            model_name='kml_shape',
            name='opacity',
            field=models.DecimalField(decimal_places=3, default=0.6, help_text='Opacity of the link. Min(0)-Max(1)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='opacity'),
        ),
        migrations.AlterField(
            model_name='kml_shape',
            name='parent_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.menu', verbose_name='parent menu'),
        ),
        migrations.AlterField(
            model_name='link',
            name='curvature',
            field=models.DecimalField(decimal_places=3, default=2.0, help_text='This field controls how curved the link will appear in the front-end. The higher the number, the less the link will be curved. Min(1)-Max(4). Accept decimal values.', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='curvature'),
        ),
        migrations.AlterField(
            model_name='link',
            name='dashed',
            field=models.BooleanField(default=False, help_text='This field, when active, will make the link stroke dashed.', verbose_name='dashed'),
        ),
        migrations.AlterField(
            model_name='link',
            name='display_name',
            field=models.CharField(max_length=25, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='link',
            name='invert_link',
            field=models.BooleanField(default=False, help_text='This field, when active, will invert the curvature of the link.', verbose_name='invert link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='links_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.links_group', verbose_name='links group'),
        ),
        migrations.AlterField(
            model_name='link',
            name='location_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_1', to='administration.location', verbose_name='location 1'),
        ),
        migrations.AlterField(
            model_name='link',
            name='location_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_2', to='administration.location', verbose_name='location 2'),
        ),
        migrations.AlterField(
            model_name='link',
            name='popup_description',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True, verbose_name='popup description'),
        ),
        migrations.AlterField(
            model_name='link',
            name='straight_link',
            field=models.BooleanField(default=False, help_text='This field, when active, will make the link line straight.', verbose_name='straight link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='weight',
            field=models.IntegerField(default=3, help_text='This field controls the weight of the link line. The higher the number, the wider the line.', null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='links_group',
            name='links_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='links color'),
        ),
        migrations.AlterField(
            model_name='links_group',
            name='opacity',
            field=models.DecimalField(decimal_places=3, default=0.6, help_text='Opacity of the link. Min(0)-Max(1)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='opacity'),
        ),
        migrations.AlterField(
            model_name='links_group',
            name='parent_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.menu', verbose_name='parent menu'),
        ),
        migrations.AlterField(
            model_name='links_group',
            name='sidebar_content',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True, verbose_name='sidebar content'),
        ),
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=24, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=24, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='overlayed_popup_content',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, help_text="<b style='font-size: 0.85rem'>* This text will be displayed on 'show more info' popup</b>", null=True, verbose_name='overlayed popup content'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='cluster_close_tags',
            field=models.BooleanField(default=True, help_text='When this field is enabled, tags located very close to each other will be grouped in clusters.', verbose_name='cluster close tags'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='footer_file',
            field=models.ImageField(blank=True, help_text='Upload a custom footer file.', upload_to='uploads/', verbose_name='footer file'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='hide_menu_group_when_unique',
            field=models.BooleanField(default=True, help_text='When there is only one Menu Group active, hide the menu groups tabs', verbose_name='hide menu group when unique'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='inherit_children_tag_locations',
            field=models.BooleanField(default=False, help_text='When this field is enabled, a tag that is parent from another tags will inherit all locations from the children that was not previously declared on the parent. If instead you want to manually declare the locations for all tags, we suggest to keep this field disabled.', verbose_name='inherit children tag locations'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='initial_latitude',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=24, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='initial latitude'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='initial_longitude',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=24, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='initial longitude'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='initial_zoom_level',
            field=models.PositiveIntegerField(default=0, help_text='Please insert a value from 0 to 13 (max zoom).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='initial zoom level'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='link_feature',
            field=models.BooleanField(default=False, help_text='When this field is enabled, the link feature will be displayed on the front-end.', verbose_name='link feature'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='map_name',
            field=models.CharField(max_length=25, verbose_name='map name'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='map_style',
            field=models.CharField(choices=[('d', 'Default (gray colored)'), ('b', 'Blue colored')], default='Default (gray colored)', max_length=15, verbose_name='map style'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.menugroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='hierarchy_level',
            field=models.IntegerField(default=0, help_text='Menus with the same number are considered siblings. Menus with lower numbers are considered parents of the ones with higher numbers. For example, a menu with the number 0 is considered parent of menus with the number 1.', verbose_name='hierarchy level'),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='simultaneous_context',
            field=models.BooleanField(default=False, help_text='When checked, this menu group context will remain active even when other menu groups are selected.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='overlayed_popup_content',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, help_text="<b style='font-size: 0.85rem'>* This text will be displayed on 'show more info' popup</b>", null=True, verbose_name='overlayed popup content'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.menu', verbose_name='parent menu'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='related_locations',
            field=models.ManyToManyField(blank=True, to='administration.location', verbose_name='related locations'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(blank=True, through='administration.Tag_relationship', to='administration.tag', verbose_name='related tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sidebar_content',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, help_text="<b style='font-size: 0.85rem'>* Leave blank to use default template</b>", null=True, verbose_name='sidebar content'),
        ),
        migrations.AlterField(
            model_name='tag_relationship',
            name='child_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tag', to='administration.tag', verbose_name='child tag'),
        ),
        migrations.AlterField(
            model_name='tag_relationship',
            name='cluster_id',
            field=models.IntegerField(blank=django.db.models.deletion.SET_NULL, default=1, help_text='Tag clusters are group of parent tags from the tag. To a cluster id be active, all tags in that id must be active. The child tag will be active if at least one of the cluster ids is active.', null=True, verbose_name='cluster ID'),
        ),
        migrations.AlterField(
            model_name='tag_relationship',
            name='parent_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_tag', to='administration.tag', verbose_name='parent tag'),
        ),
    ]
