# Generated by Django 5.0 on 2026-03-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_menunametranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menunametranslation',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
