# Generated by Django 5.0 on 2026-03-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_rename_menu_id_menunametranslation_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunametranslation',
            name='language_code',
            field=models.CharField(choices=[('pt-BR', '🇧🇷 Portuguese'), ('en', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='pt-BR', max_length=20, verbose_name='Language'),
        ),
    ]
