# Generated by Django 5.0 on 2026-03-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0035_alter_menunametranslation_language_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menunametranslation',
            unique_together={('menu', 'language_code')},
        ),
    ]
