# Generated by Django 5.0 on 2026-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0037_alter_menunametranslation_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_configuration',
            name='default_content_language',
            field=models.CharField(choices=[('pt-BR', '🇧🇷 Portuguese'), ('en-US', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='pt-BR', max_length=20, verbose_name='Default Content Language'),
        ),
    ]
