# Generated by Django 5.0 on 2026-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0038_map_configuration_default_content_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunametranslation',
            name='language_code',
            field=models.CharField(choices=[('pt-BR', '🇧🇷 Portuguese'), ('en-US', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='en-US', max_length=20, verbose_name='Language'),
        ),
    ]
