# Generated by Django 5.0 on 2026-03-30 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_alter_menunametranslation_language_code'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menunametranslation',
            name='menu_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='menunametranslation',
            table='menu_name_translation',
        ),
        migrations.CreateModel(
            name='TitleTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element_id', models.CharField(max_length=20)),
                ('language_code', models.CharField(choices=[('pt-BR', '🇧🇷 Portuguese'), ('en-US', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='en-US', max_length=20, verbose_name='Language')),
                ('element_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Title Translations',
                'db_table': 'titletranslations',
            },
        ),
    ]
