# Generated by Django 5.0 on 2026-04-06 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_alter_menu_name_alter_menunametranslation_menu_name_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titletranslations',
            name='element_table',
        ),
        migrations.CreateModel(
            name='TitleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element_id', models.PositiveIntegerField()),
                ('language_code', models.CharField(choices=[('pt-BR', '🇧🇷 Portuguese'), ('en-US', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='en-US', max_length=20, verbose_name='Language')),
                ('element_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Title Translations',
                'db_table': 'titletranslation',
            },
        ),
        migrations.DeleteModel(
            name='MenuNameTranslation',
        ),
        migrations.DeleteModel(
            name='TitleTranslations',
        ),
        migrations.AddConstraint(
            model_name='titletranslation',
            constraint=models.UniqueConstraint(fields=('element_table', 'element_id', 'language_code'), name='unique_translation_per_element_language'),
        ),
    ]
