# Generated by Django 5.0 on 2026-04-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_remove_titletranslations_element_table_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuNameTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('pt-BR', '🇧🇷 Portuguese'), ('en-US', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='en-US', max_length=20, verbose_name='Language')),
            ],
            options={
                'db_table': 'menu_name_translation',
            },
        ),
        migrations.RemoveConstraint(
            model_name='titletranslation',
            name='unique_translation_per_element_language',
        ),
        migrations.RenameField(
            model_name='titletranslation',
            old_name='element_table',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='titletranslation',
            old_name='element_id',
            new_name='object_id',
        ),
        migrations.AddConstraint(
            model_name='titletranslation',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'language_code'), name='unique_translation_per_element_language'),
        ),
        migrations.AddField(
            model_name='menunametranslation',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.menu'),
        ),
        migrations.AlterUniqueTogether(
            name='menunametranslation',
            unique_together={('menu', 'language_code')},
        ),
    ]
