# Generated by Django 5.0 on 2026-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0042_menunametranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationsGeneratorTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Generate Translations',
                'verbose_name_plural': 'Generate Translations',
                'managed': False,
            },
        ),
    ]
