# Generated by Django 5.0 on 2026-04-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_translationsgeneratortool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationsGeneratorTool',
        ),
    ]
