# Generated by Django 5.0 on 2026-04-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0044_delete_translationsgeneratortool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_configuration',
            name='default_content_language',
            field=models.CharField(choices=[('pt', '🇧🇷 Portuguese'), ('en', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='pt', max_length=20, verbose_name='Default Content Language'),
        ),
        migrations.AlterField(
            model_name='menunametranslation',
            name='language_code',
            field=models.CharField(choices=[('pt', '🇧🇷 Portuguese'), ('en', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='en', max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='titletranslation',
            name='language_code',
            field=models.CharField(choices=[('pt', '🇧🇷 Portuguese'), ('en', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='en', max_length=20, verbose_name='Language'),
        ),
    ]
