# Generated by Django 5.0 on 2026-04-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0045_alter_map_configuration_default_content_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuNameTranslation',
        ),
    ]
