# Generated by Django 5.0 on 2026-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0046_delete_menunametranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titletranslation',
            name='language_code',
            field=models.CharField(choices=[('pt', '🇧🇷 Portuguese'), ('en', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], max_length=20, verbose_name='Language'),
        ),
    ]
