# Generated by Django 5.0 on 2026-04-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0047_alter_titletranslation_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code2', models.CharField(max_length=2)),
                ('code4', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=25)),
                ('flag', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Language Options',
                'db_table': 'languageoptions',
            },
        ),
        migrations.AddField(
            model_name='map_configuration',
            name='automatic_translation_languages',
            field=models.ManyToManyField(blank=True, to='administration.languageoption'),
        ),
    ]
