# Generated by Django 5.0 on 2026-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0048_languageoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_configuration',
            name='automatic_translation_languages',
        ),
        migrations.AddField(
            model_name='map_configuration',
            name='automatic_translation_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
