# Generated by Django 5.0 on 2026-04-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0049_remove_map_configuration_automatic_translation_languages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageOption',
        ),
        migrations.RemoveField(
            model_name='map_configuration',
            name='automatic_translation_languages',
        ),
    ]
