# Generated by Django 5.0 on 2026-04-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0050_delete_languageoption_and_more'),
        ('clients', '0006_alter_languageoption_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_configuration',
            name='automatic_translation_languages',
            field=models.ManyToManyField(blank=True, to='clients.languageoption'),
        ),
    ]
