# Generated by Django 5.0 on 2026-04-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0051_map_configuration_automatic_translation_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_configuration',
            name='default_content_language',
            field=models.CharField(choices=[('pt', '🇧🇷 Portuguese'), ('en', '🇺🇸 English'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='pt', max_length=20, verbose_name='Default content canguage'),
        ),
    ]
