# Generated by Django 5.0 on 2026-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0052_alter_map_configuration_default_content_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='menugroup',
            name='translatable',
            field=models.BooleanField(default=True),
        ),
    ]
