# Generated by Django 5.0 on 2026-04-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0053_menugroup_translatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='kml_shape',
            name='translatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='link',
            name='translatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='links_group',
            name='translatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='translatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='translatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='translatable',
            field=models.BooleanField(default=True),
        ),
    ]
