# Generated by Django 5.0 on 2026-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0054_kml_shape_translatable_link_translatable_and_more'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_configuration',
            name='automatic_translation_languages',
            field=models.ManyToManyField(blank=True, help_text='After the elementios creation, an automatic translation will be added for each selected language.', to='languages.languageoption'),
        ),
    ]
