# Generated by Django 5.0 on 2026-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0055_alter_map_configuration_automatic_translation_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_configuration',
            name='default_content_language',
            field=models.CharField(choices=[('en', '🇺🇸 English'), ('pt', '🇧🇷 Português'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='pt', max_length=20, verbose_name='Default content canguage'),
        ),
        migrations.AlterField(
            model_name='titletranslation',
            name='language_code',
            field=models.CharField(choices=[('en', '🇺🇸 English'), ('pt', '🇧🇷 Português'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], max_length=20, verbose_name='Language'),
        ),
    ]
