# Generated by Django 5.0 on 2026-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0056_alter_map_configuration_default_content_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_configuration',
            name='default_content_language',
            field=models.CharField(choices=[('en', '🇺🇸 English'), ('pt', '🇧🇷 Português'), ('es', '🇪🇸 Español'), ('de', '🇩🇪 Deutsch'), ('ko', '🇰🇷 한국어')], default='pt', max_length=20, verbose_name='Default content language'),
        ),
    ]
