# Generated by Django 5.0 on 2026-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0057_alter_map_configuration_default_content_language'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleTranslation',
            new_name='NameTranslation',
        ),
        migrations.AlterModelOptions(
            name='nametranslation',
            options={'verbose_name_plural': 'Name Translations'},
        ),
        migrations.RemoveConstraint(
            model_name='nametranslation',
            name='unique_translation_per_element_language',
        ),
        migrations.AddConstraint(
            model_name='nametranslation',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'language_code'), name='unique_name_translation_per_element_language'),
        ),
        migrations.AlterModelTable(
            name='nametranslation',
            table='nametranslation',
        ),
    ]
