# Generated by Django 5.0 on 2026-08-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0058_rename_titletranslation_nametranslation_and_more'),
        ('clients', '0009_auto_20260420_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='display_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='automatic_translation_languages',
            field=models.ManyToManyField(blank=True, help_text='After the elementios creation, an automatic translation will be added for each selected language.', to='clients.languageoption', verbose_name='automatic translation languages'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='hierarchy_level',
            field=models.IntegerField(default=0, help_text='Menus with the same number are considered siblings. Menus with lower numbers are considered parents of the ones with higher numbers. For example, a menu with the number 0 is considered parent of menus with the number 1.'),
        ),
    ]
