
class StringConstraints:
    ELEMENT_TYPE_NAME_SIZE = 50
    ELEMENT_TITLE_SIZE = 100
    POPUP_CONTENT_SIZE = 20000
    
    LANGUAGE_CODE_MAX_CHAR_NUMBER = 20
    
    LANGUAGE_CODE_2_SIZE = 2
    LANGUAGE_CODE_4_SIZE = 5
    LANGUAGE_NAME_SIZE = 25
    LANGUAGE_FLAG_SIZE = 3